name: user_repository
description: The repo that handles users
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # equatable: ^2.0.5
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.9.2
  # firebase_storage: ^11.6.0
  rxdart: ^0.27.7
  path: ^1.8.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
uses-material-design: true